# Matlab/Octave syntax for tinyedit
extensions = m,mat
keywords = function,end,if,else,elseif,for,while,switch,case,otherwise,return,break,continue,global,persistent,classdef,properties,methods,try,catch
quote_chars = '"
line_comment = %
block_comment_start = %{
block_comment_end = %}

filetype = Matlab/Octave
